# Use root/example as user/password credentials
version: '3.1'
volumes:
  App:
services:
  dev:
    container_name: app
    build:
      context: .
    ports:
      - 80:80
      - 81:81
    image: devops-contracting-app
  prod:
    container_name: app
    build:
      context: .
    ports:
      - 80:80
      - 81:81
    image: devops-contracting-app
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
